const swaggerAutogen = require("swagger-autogen")();

import { config } from "#/config/constants";
import fixtures from "#/config/server/fixtures.json";

const doc = {
  info: {
    version: "1.0.0",
    title: "swagger-generator",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${config.serverPort}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Organization",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "any description...",
    },
  },
  definitions: {
    Entity: {
      ...fixtures.service.organization.entity,
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = [
  config.script === "swagger"
    ? "dist/src/routes/index.js"
    : "src/routes/index.ts",
];

(async () => {
  await swaggerAutogen(outputFile, endpointsFiles, doc);
})();
